all: final

final: chess.o output.o dataTypes.o
        g++ chess.o output.o dataTypes.o -o chess
  
chess.o: chess.cpp
        g++ -c chess.cpp

output.o: output.cpp
        g++ -c output.cpp

dataTypes.o: dataTypes.cpp
        g++ -c dataTypes.cpp
        
clean:
        rm chess.o
        rm output.o
        rm dataTypes.o
        rm chess
